services:
  - type: web
    name: call-transcriber # You can change this name if you like
    runtime: python
    # Removed pythonVersion key - Render will use a default Python 3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      # IMPORTANT: Create an Environment Group in Render named 'call-transcriber-secrets'
      # Add ALL your secrets (RevAI key, Airtable keys/IDs, R2 keys/IDs/Domain/Bucket) there.
      - fromGroup: call-transcriber-secrets
      # Alternatively, define individual keys and manage values in the dashboard
      # - key: PYTHON_VERSION # Example if needed elsewhere
      # - key: REV_AI_API_KEY
      #   sync: false # Set sync to false to manage value only in Render dashboard
      # ... add other keys similarly if not using a group ... 